#!node

// process.argv[0] in node's path
// process.argv[1] is this file full path location
// process.argv[2] is finally our first 'true' argument
// console.log(process.argv[2])

const fs = require('fs')

filename = process.argv[2]

const data = fs.readFileSync(filename);  // readFileSync is blocking

const graph = JSON.parse(data);

// graph.factors.forEach(f=>{
//   console.log(f.factor_id)
// })

// remove factors of type 'loop-closure'
graph.factors = graph.factors.filter(f=>{ 
  return f.type!="loop-closure";
});

console.log(JSON.stringify(graph))
